import { existsSync, statSync } from "node:fs";
import { sniffFile } from "../library/analyze.js";
import { addMoment, refreshFootageAnalysis } from "../library/footage.js";
import { GenerationSchema, normaliseTags, type Generation, type LibraryAsset, type Moment } from "../library/schema.js";
import { addAsset, LibraryError, loadIndex } from "../library/store.js";
import { stillEligibility, type GenerationMode } from "./eligibility.js";

/**
 * Bring a finished generated clip into the library.
 *
 * Claude calls Higgsfield, saves what comes back, and runs this. The clip becomes a library video asset
 * whose provenance says what made it (the model, the prompt, the job), so the report can say so and a
 * re-render uses this file and never asks Higgsfield again. It is **generic, never identity**, and it
 * starts **pending**: a person approves each generated clip before a reel can use it.
 */

export interface RegisterInput {
  file: string;
  mode: GenerationMode;
  model: string;
  prompt: string;
  beat?: string | undefined;
  jobId?: string | undefined;
  credits?: number | undefined;
  /** For `animate-still`: the library image it was made from. */
  fromAsset?: string | undefined;
}

export interface Registered {
  asset: LibraryAsset;
  moment: Moment;
  existed: boolean;
}

export async function registerGenerated(input: RegisterInput): Promise<Registered> {
  if (!existsSync(input.file) || !statSync(input.file).isFile()) throw new LibraryError(`${input.file} is not a file`);
  const sniffed = sniffFile(input.file);
  if (!sniffed || sniffed.mediaType !== "video") throw new LibraryError("a generated clip has to be a video");
  if (!input.model.trim()) throw new LibraryError("--model is required: which model made it");
  if (!input.prompt.trim()) throw new LibraryError("--prompt is required: what it was asked for");

  if (input.mode === "animate-still") {
    const still = loadIndex().assets.find((a) => a.id === input.fromAsset);
    if (!still) throw new LibraryError("animate-still needs --from-asset <the library image it was made from>");
    const verdict = stillEligibility(still);
    if (!verdict.ok) throw new LibraryError(`${still.name} may not be animated: ${verdict.reason}`);
  }

  const generation: Generation = GenerationSchema.parse({
    provider: "higgsfield",
    mode: input.mode,
    model: input.model.trim().slice(0, 80),
    prompt: input.prompt.trim().slice(0, 1200),
    ...(input.jobId ? { jobId: input.jobId.slice(0, 120) } : {}),
    ...(input.credits !== undefined ? { credits: input.credits } : {}),
    ...(input.beat ? { beat: input.beat.slice(0, 40) } : {}),
    ...(input.fromAsset ? { fromAsset: input.fromAsset } : {}),
    at: new Date().toISOString(),
  });

  const slug = generation.model.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const { asset, existed } = addAsset(input.file, {
    name: `Generated: ${input.beat ?? generation.model}`.slice(0, 120),
    assetKind: "generic",
    tags: normaliseTags(["generated", "ai", "higgsfield", input.mode, slug].filter(Boolean)),
    provenance: { source: "generated", generation, note: `AI-generated by ${generation.model} on Higgsfield${input.jobId ? `, job ${input.jobId}` : ""}` },
    mediaType: "video",
    // Pending: a person approves each generated clip.
    review: { state: "pending" },
  });

  // Measure it (size, length, filmstrip), then give it its one moment: the whole clip.
  const measured = await refreshFootageAnalysis(asset.id);
  const length = measured.analysis.durationSeconds ?? 0;
  const existing = measured.footage?.moments[0];
  if (existing) return { asset: measured, moment: existing, existed };
  if (!(length >= 0.5)) throw new LibraryError("could not read how long the generated clip is");
  const { asset: withMoment, moment } = addMoment(asset.id, { label: `Generated: ${input.beat ?? "clip"}`, in: 0, out: Math.floor(length * 1000) / 1000, tags: ["generated"] }, "generated");
  return { asset: withMoment, moment, existed };
}
